"""add helpful_count to review 

Revision ID: 0ef2acc2f9f0
Revises: 
Create Date: 2026-07-10 15:47:18.892785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef2acc2f9f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpful_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funny_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('funny_count')
        batch_op.drop_column('helpful_count')

    # ### end Alembic commands ###
