"""add demo_path

Revision ID: 1e09a762e6cb
Revises: 0ef2acc2f9f0
Create Date: 2026-07-11 18:48:29.083641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e09a762e6cb'
down_revision = '0ef2acc2f9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_path', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('demo_path')

    # ### end Alembic commands ###
