"""add profile comments and comments_enabled flag

Revision ID: 489cbe452040
Revises: 1e09a762e6cb
Create Date: 2026-07-12 18:44:59.683434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489cbe452040'
down_revision = '1e09a762e6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('comments_enabled')

    # ### end Alembic commands ###
