"""add 2fa toggle and username setup flag

Revision ID: 801769bf969e
Revises: 8939b56f4624
Create Date: 2026-07-18 00:28:23.281096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801769bf969e'
down_revision = '8939b56f4624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_username_setup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('needs_username_setup')
        batch_op.drop_column('two_fa_enabled')

    # ### end Alembic commands ###
