"""add revenue to gamestats and price_paid to purchase

Revision ID: 88da76807e0b
Revises: 489cbe452040
Create Date: 2026-07-14 22:50:22.088650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88da76807e0b'
down_revision = '489cbe452040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('purchased_at')
        batch_op.drop_column('price_paid')

    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('revenue')

    # ### end Alembic commands ###
