"""add email_verified and firebase_uid to user, add login_otp table

Revision ID: 8939b56f4624
Revises: 88da76807e0b
Create Date: 2026-07-17 00:42:57.622486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8939b56f4624'
down_revision = '88da76807e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_user_firebase_uid', ['firebase_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
