"""add gift model

Revision ID: 9a0cbbb7114a
Revises: 5132dad70839
Create Date: 2026-08-28 20:56:30.478217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0cbbb7114a'
down_revision = '5132dad70839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_item_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_item_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('game_follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_follow_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_follow_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_game_id'))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_game_id'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    with op.batch_alter_table('game_follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_follow_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_follow_game_id'))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_item_game_id'))

    # ### end Alembic commands ###
