"""add hackclub_id and has_password to user

Revision ID: b2daf1499aa9
Revises: b74e3bb8a280
Create Date: 2026-08-16 17:16:38.386019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2daf1499aa9'
down_revision = 'b74e3bb8a280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hackclub_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('has_password', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_hackclub_id', ['hackclub_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_hackclub_id', type_='unique')
        batch_op.drop_column('has_password')
        batch_op.drop_column('hackclub_id')

    # ### end Alembic commands ###