"""add followed_at to game_follow

Revision ID: b74e3bb8a280
Revises: f11de0a5e990
Create Date: 2026-08-12 22:29:12.488619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74e3bb8a280'
down_revision = 'f11de0a5e990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('game_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), nullable=True))
        batch_op.alter_column('view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('title')
        batch_op.drop_column('vlog_url')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('link')

    with op.batch_alter_table('update_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_type', sa.String(length=10), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.INTEGER(), nullable=False))
        batch_op.drop_column('vote_type')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=250), nullable=True))

    with op.batch_alter_table('game_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vlog_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    with op.batch_alter_table('game_follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('followed_at')

    # ### end Alembic commands ###
